# Generated by Django 3.2.6 on 2021-08-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countRemaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'InActive')], default=False),
        ),
    ]
